export enum GameEvents {
  BUILD_START = 'BUILD_START',
  BUILD_END = 'BUILD_END',

  POSITION_START = 'POSITION_START',
  POSITION_END = 'POSITION_END',

  BATTLE_START = 'BATTLE_START',
  BATTLE_END = 'BATTLE_END',

  FINISH_START = 'FINISH_START',
  FINISH_END = 'FINISH_END'
}